name: Build self-contained executables for multiple platforms

on:
  release:
    types: [published]


jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            TARGET: ubuntu-22.04
            CMD_BUILD: >
              pyinstaller --noconfirm build-executables/dc-build-ubuntu-22.04.spec && cd dist && tar -czf ../decode-config-ubuntu-22.04.tar.gz decode-config
            OUT_FILE_NAME: decode-config-ubuntu-22.04.tar.gz
            ASSET_MIME: application/x-gzip
          - os: ubuntu-20.04
            TARGET: ubuntu-20.04
            CMD_BUILD: >
              pyinstaller --noconfirm build-executables/dc-build-ubuntu-20.04.spec && cd dist && tar -czf ../decode-config-ubuntu-20.04.tar.gz decode-config
            OUT_FILE_NAME: decode-config-ubuntu-20.04.tar.gz
            ASSET_MIME: application/x-gzip
          - os: macos-12
            TARGET: macos-12
            CMD_BUILD: >
              pyinstaller --noconfirm build-executables/dc-build-macos.spec && cd dist && zip -r9 ../decode-config-macos-12.zip decode-config
            OUT_FILE_NAME: decode-config-macos-12.zip
            ASSET_MIME: application/zip
          - os: macos-13
            TARGET: macos-13
            CMD_BUILD: >
              pyinstaller --noconfirm build-executables/dc-build-macos.spec && cd dist && zip -r9 ../decode-config-macos-13.zip decode-config
            OUT_FILE_NAME: decode-config-macos-13.zip
            ASSET_MIME: application/zip
          - os: macos-latest-large
            TARGET: macos-14-large
            CMD_BUILD: >
              pyinstaller --noconfirm build-executables/dc-build-macos.spec && cd dist && zip -r9 ../decode-config-macos-14.zip decode-config
            OUT_FILE_NAME: decode-config-macos-14.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller --noconfirm build-executables/dc-build-windows.spec && copy dist/decode-config.exe .
            OUT_FILE_NAME: decode-config.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # Install pip and pyinstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build self-contained executable with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Upload asset for ${{matrix.TARGET}}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{matrix.OUT_FILE_NAME}}
